AIM: - TO CONTROL A LED USING ARDUINO AND SIMPLE PROGRAM.
MATERIAL REQUIRED:-
1. ARDUINO UNO
2. PROGRAMMING CABLE
3. LAPTOP
4. LED
SOFTWARE: - ARDUINO IDE 1.8.19
PROGRAMMING LANGUAGE: - C++
CONNECTIONS: - LED (+) TO ARDUINO PIN 12
              LED (-) TO ARDUINO GND
